#!/usr/bin/env python3
"""Convert KeyCopier's key_formats.c (MIT, zinongli/KeyCopier) into a C++ table for the Mayhem app.
tan((180-drill_angle)/2 deg) is precomputed so the device needs no libm."""
import re, math, sys
src = open(sys.argv[1]).read()
blocks = re.findall(r"\{\s*\.manufacturer.*?\}\s*[,;]?", src, re.S)
rows = []
for b in blocks:
    b = re.sub(r"//[^\n]*", "", b)
    f = dict(re.findall(r"\.(\w+)\s*=\s*(\"[^\"]*\"|[-\d.]+)", b))
    g = lambda k, d="0": f.get(k, d)
    ang = float(g("drill_angle", "90"))
    tan = math.tan(math.radians((180 - ang) / 2))
    rows.append(f'    {{{g("manufacturer")}, {g("format_name")}, {g("sides")}, {g("stop")}, '
                f'{g("first_pin_inch")}f, {g("pin_increment_inch")}f, {g("pin_num")}, {g("pin_width_inch")}f, '
                f'{tan:.5f}f, {g("elbow_inch")}f, {g("uncut_depth_inch")}f, {g("depth_step_inch")}f, '
                f'{g("min_depth_ind")}, {g("max_depth_ind")}, {g("macs")}, {g("clearance")}, {g("last_pin_inch")}f}},')
print(f"// GENERATED by tools/gen_formats.py from zinongli/KeyCopier key_formats.c (MIT). {len(rows)} formats.")
print("// Lengths in inches.")
print('#include "key_formats.hpp"\nnamespace ui::external_app::key_copier {')
print("const KeyFormat all_formats[FORMAT_NUM] = {")
print("\n".join(rows))
print("};\n}")
print(f"// count={len(rows)}", file=sys.stderr)
